os: windows
language: shell
before_install:
    - choco install python
    - python --version
    - python -m pip install -U pip
    - python -m pip install meson
    - choco install ninja
script:
    - meson .out
    - ninja -C .out
    - .out\app.exe